app:
  aws:
    region: eu-north-1
    dynamo-db:
      table-name: image-metadata
      endpoint: http://localhost:4566
    s3:
      endpoint: http://localhost:4566
      bucket-name: image-recognitioner
      key-prefix: images/
    rekognition:
      endpoint: http://localhost:4566
      moderation-min-confidence: 60.0