app:
  aws:
    region: eu-north-1
    dynamo-db:
      table-name: ImageMetadata
      endpoint: http://localhost:8000
    s3:
      endpoint: http://localhost:4566
      bucket-name: image-recognitioner-images
      key-prefix: images/